### ISSUE TITLE
Picture in Picture not working in IOS but working in Android 

### ISSUE THREAD

**Issue by Amansingla97** [gunschu/jitsi_meet#173] opened 2020-12-10 23:58 UTC
In IOS : 
![IMG_5327](https://user-images.githubusercontent.com/20012612/101844117-b3ded300-3b71-11eb-94d4-17284501f6be.PNG)
Whenever PIP is enabled, video goes into pip mode but the background is always black.

**Comment by jimmyjose-dev** [comment] 2020-12-11 12:43
#120 the thread

or specific comment https://github.com/gunschu/jitsi_meet/issues/120#issuecomment-704934715

**Comment by tuantvu** [comment] 2021-01-25 01:32
Closing due to OS working as designed.

**Closed as completed by tuantvu** 2021-01-25 01:32 UTC
Labels: unrelated to plugin

**Comment by nsumithradeveloper** [comment] 2021-02-16 01:59
> In IOS :
> ![IMG_5327](https://user-images.githubusercontent.com/20012612/101844117-b3ded300-3b71-11eb-94d4-17284501f6be.PNG)
> Whenever PIP is enabled, video goes into pip mode but the background is always black.

Does this happened in phone or in simulator

**Comment by aartiaparekh** [comment] 2021-03-05 12:18
@Amansingla97 You got any solution? I am also stuck in same flow in ios.

**Comment by jimmyjose-dev** [comment] 2021-03-14 17:41
#218
