### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by marcoberetta96** [gunschu/jitsi_meet#178] opened 2020-12-20 21:34 UTC
I read that customizing the layout is currently not possible.
Is it on roadmap to have the possibility to bring the own layout (colors, widget positions, ...) ?

**Comment by jagadish-pattanaik** [comment] 2020-12-22 04:56
Yeah I am also looking upto that...as I also want to change the background colour to black and many other things.

**Comment by IggyBlob** [comment] 2021-01-14 14:17
I'm interested in that, too. More specifically, I'm trying to restrain Jitsi to a certain area of the screen such that parts of the host app are still visible. Is there any way to achieve this?

**Comment by tuantvu** [comment] 2021-01-25 01:40
I think there were attempts to make this a platformview, but not sure how successful it's been. Maybe check some of the forks of this project?

**Comment by tuantvu** [comment] 2021-04-02 07:33
making this duplicate of #79

**Closed as completed by tuantvu** 2021-04-02 07:33 UTC
Labels: duplicate
