### ISSUE TITLE
Could you please implement an end meeting functionality from the dart code ?

### ISSUE THREAD

**Issue by devidasm** [gunschu/jitsi_meet#45] opened 2020-05-30 07:48 UTC
In my app, there is a functionality to end the meeting programmatically when the host stopped the meeting. Please check about this https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#leave

**Comment by tuantvu** [comment] 2020-06-27 20:44
Duplicate of #39

**Closed as completed by tuantvu** 2020-06-27 20:44 UTC
Labels: duplicate

**Comment by devidasm** [comment] 2020-07-02 09:08
Sorry ? It seems you misunderstand the question. Anyway I already solved this problem by editing the plugin source.
