### ISSUE TITLE
Deeplinking issue in iOS

### ISSUE THREAD

**Issue by tusharsonawanes** [gunschu/jitsi_meet#182] opened 2021-01-05 07:10 UTC
Hello, how to enable deeplinks in iOS version of the same ?

**Comment by tuantvu** [comment] 2021-01-25 01:50
@tusharsonawanes I'm unable to understand what it is you are needing.

**Comment by tuantvu** [comment] 2021-01-25 01:51
duplicate of #184

**Closed as completed by tuantvu** 2021-01-25 01:51 UTC
Labels: duplicate

**Comment by tusharsonawanes** [comment] 2021-01-25 01:52
> @tusharsonawanes I'm unable to understand what it is you are needing.

@tuantvu what I want is, when the use clicks on the meeting link, the "app" should be opened. Got it ?
