### ISSUE TITLE
[FEATURE]: participantJoin and participantLeft listener 

### ISSUE THREAD

**Issue by IkhwanSI13** [gunschu/jitsi_meet#252] opened 2021-04-19 06:41 UTC
**Description**

I try to do something when the participant joins or left from the meeting. 

**Is the feature supported by Jitsi?**
jitsi_meet Flutter plugin is dependent on the [Android](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk) and [iOS](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk) SDK from jitsi.org. If those SDKs do not support a feature, we also can not add it.
* [x] Yes: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk & https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk
* [ ] No

**Describe the solution you'd like**
A listener like onConferenceWillJoin, onConferenceJoined, etc

**Comment by tuantvu** [comment] 2021-04-20 15:21
Duplicate of #231

**Closed as completed** 2021-04-20 15:21 UTC
Labels: duplicate, enhancement
