### ISSUE TITLE
Flutter null-safety

### ISSUE THREAD

**Issue by fabriciosf1** [gunschu/jitsi_meet#221] opened 2021-03-23 21:17 UTC
Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

Error:
jitsi_meet-0.3.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPlugin.kt:65:37: warning: 'Registrar' is deprecated. Deprecated in Java
        fun registerWith(registrar: Registrar) {                        
                                    ^                             
jitsi_meet-0.3.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPlugin.kt:154:30: warning: parameter 'call' is never used
    private fun closeMeeting(call: MethodCall, result: Result) {       

jitsi_meet-0.3.0\android\src\main\kotlin\com\gunschu\jitsi_meet\JitsiMeetPluginActivity.kt:43:25: warning: unnecessary safe call on a non-null receiver of type Intent
            when (intent?.action) {
                        ^

**Comment by tuantvu** [comment] 2021-04-03 22:17
@fabriciosf1 Making this duplicate of #197. Pre-release 4.0.0 is out, try it out: https://pub.dev/packages/jitsi_meet/versions/4.0.0-nullsafety.0

**Closed as completed by tuantvu** 2021-04-03 22:17 UTC
Labels: bug, chore
