### ISSUE TITLE
iOS SDK not working with Xcode 12.2, jitsi_meet 1.0.0, JitsiMeetSDK 2.10.2, flutter v 1.22.3

### ISSUE THREAD

**Issue by NVQuan** [gunschu/jitsi_meet#136] opened 2020-11-13 08:23 UTC
/Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:23:83: error:
    'PiPViewCoordinator' is not a member type of 'JitsiMeet'
        public static func == (a: JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position) -> Swift.Bool
                                                                            ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:29:52: error:
    'PiPViewCoordinator' is not a member type of 'JitsiMeet'
      public var initialPositionInSuperview: JitsiMeet.PiPViewCoordinator.Position
                                             ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:32:39: error:
    'PiPViewCoordinatorDelegate' is not a member type of 'JitsiMeet'
      weak public var delegate: JitsiMeet.PiPViewCoordinatorDelegate?
                                ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:35:42: error:
    'AnimationCompletion' is not a member type of 'JitsiMeet'
      public func show(completion: JitsiMeet.AnimationCompletion? = nil)
                                   ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:36:42: error:
    'AnimationCompletion' is not a member type of 'JitsiMeet'
      public func hide(completion: JitsiMeet.AnimationCompletion? = nil)
                                   ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:51:62: error:
    'JMCallKitListener' is not a member type of 'JitsiMeet'
      @objc public static func addListener(_ listener: JitsiMeet.JMCallKitListener)
                                                       ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:52:65: error:
    'JMCallKitListener' is not a member type of 'JitsiMeet'
      @objc public static func removeListener(_ listener: JitsiMeet.JMCallKitListener)
                                                          ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:72:21: error:
    'PiPViewCoordinator' is not a member type of 'JitsiMeet'
    extension JitsiMeet.PiPViewCoordinator.Position : Swift.Equatable {}
              ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface:73:21: error:
    'PiPViewCoordinator' is not a member type of 'JitsiMeet'
    extension JitsiMeet.PiPViewCoordinator.Position : Swift.Hashable {}
              ~~~~~~~~~ ^
    JitsiMeet.JitsiMeet:1:12: note: 'JitsiMeet' declared here
    open class JitsiMeet : NSObject {
               ^
    /Users/username/Development/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-1.0.0/ios/Classes/JitsiViewController.swift:2:8: error: failed to build module 'JitsiMeet' from its module
    interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)', may have used features that aren't supported by this compiler, 'Apple Swift
    version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)'
    import JitsiMeet
           ^
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build

**Comment by MirzaUkas** [comment] 2020-11-13 16:13
Same issues, any solution for this ?

**Comment by obyazilim** [comment] 2020-11-14 13:25
Same issues  :(

**Comment by mfa01** [comment] 2020-11-15 08:22
Hello
I have same issue, it happened with me before but I increased. the version of JITSI, but its no longer working now

any solution?

**Comment by buzzwin** [comment] 2020-11-15 14:48
Run "flutter clean iOS".Remove podfile.lock and podfile.A "pod repo update" may be necessary in some cases.Build again using flutter. The pod file will be created again . It should fix the problem. As always keep backups. I am able to test using the configs and versions mentioned.

**Comment by jimmyjose-dev** [comment] 2020-11-15 16:02
This is a Xcode/Cocoapods issue and If @buzzwin 's solution doesn't work out... 

@MirzaUkas @obyazilim @mfa01 ...give this a shot...
@NVQuan as the error denotes `'PiPViewCoordinator' is not a member type of 'JitsiMeet'`  just remove it from that line.

open the file at

`/Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface` 

goto line _line 23_

remove the word **JitsiMeet.** from  this line
`JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position`

and should look like

`PiPViewCoordinator.Position, b: PiPViewCoordinator.Position`

Do this for all the error lines in the same file, you may do a string replace.
<img src="https://dl.dropboxusercontent.com/s/9hi1xfhv53s0jwo/search.png" />

Press Run/Build 
if you get an error like `PhaseScriptExecution failed with a nonzero exit code` just press run/build again

Building for simulator change in - **x86_64-apple-ios-simulator.swiftinterface**
Building for device change in - **arm64-apple-ios.swiftinterface**

[Download Simulator fixed file](https://dl.dropboxusercontent.com/s/w08g1643yogiot0/x86_64-apple-ios-simulator.swiftinterface)
place it inside
`/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/`

<img src="https://dl.dropboxusercontent.com/s/xbk6fjps7cc6rt2/result.png" />

**Comment by mfa01** [comment] 2020-11-17 00:18
@Snapworks Thanks for helping, its working!

**Comment by NVQuan** [comment] 2020-11-17 02:10
@Snapworks Thanks Very Much!!! It worked like a charm!!!

**Comment by jimmyjose-dev** [comment] 2020-11-17 06:44
@tuantvu bro, should we add few things in wiki

**Comment by real1900** [comment] 2020-11-17 10:22
> This is a Xcode/Cocoapods issue and If @buzzwin 's solution doesn't work out...
> 
> @MirzaUkas @obyazilim @mfa01 ...give this a shot...
> @NVQuan as the error denotes `'PiPViewCoordinator' is not a member type of 'JitsiMeet'` just remove it from that line.
> 
> open the file at
> 
> `/Users/username/Documents/Workspace/project/inet/vapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64-apple-ios.swiftinterface`
> 
> goto line _line 23_
> 
> remove the word **JitsiMeet.** from this line
> `JitsiMeet.PiPViewCoordinator.Position, b: JitsiMeet.PiPViewCoordinator.Position`
> 
> and should look like
> 
> `PiPViewCoordinator.Position, b: PiPViewCoordinator.Position`
> 
> Do this for all the error lines in the same file, you may do a string replace.
> ![](https://camo.githubusercontent.com/485c74c25befb14eaffd6d58e98f4e7423651b00d0a7e2a33093d3345ded3265/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f3968693178666876353373306a776f2f7365617263682e706e67)
> 
> Press Run/Build
> if you get an error like `PhaseScriptExecution failed with a nonzero exit code` just press run/build again
> 
> Building for simulator change in - **x86_64-apple-ios-simulator.swiftinterface**
> Building for device change in - **arm64-apple-ios.swiftinterface**
> 
> [Download Simulator fixed file](https://dl.dropboxusercontent.com/s/w08g1643yogiot0/x86_64-apple-ios-simulator.swiftinterface)
> place it inside
> `/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/`
> 
> ![](https://camo.githubusercontent.com/f6e5c2ba33fe67656f91bfffb1229f0329d75b6126b1c2f01eff8656599ef711/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f78626b36666a7073376363367274322f726573756c742e706e67)

Is there a permanent fix for this?

**Comment by tuantvu** [comment] 2020-11-17 17:49
@real1900 We'll try, but I've had to do a pod repo update at least each time the Jitsi sdk is updated.

@Snapworks I don't know how to reach you via a different means on the GitHub app, so asking you here if you would like to join @buzzwin and I in managing this project. Let me know, thanks.

**Comment by jimmyjose-dev** [comment] 2020-11-17 18:11
> @Snapworks I don't know how to reach you via a different means on the GitHub app, so asking you here if you would like to join @buzzwin and I in managing this project. Let me know, thanks.

@tuantvu 
Sure Bro 👍

**Comment by jimmyjose-dev** [comment] 2020-11-18 17:50
@tuantvu 
🧐 only half my message came through on top, I will be happy to assist you and @buzzwin in managing this project.

![Hi5ForTuantvu](https://dl.dropbox.com/s/n32dq4fle8fh7l4/internet-high-five.jpg)

**Comment by real1900** [comment] 2020-12-02 15:04
Why was this issue closed exactly ? 

The problem still exists

**Comment by nouhouari** [comment] 2020-12-07 09:50
I'm facing the same issue.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (**Channel stable, 1.22.4**, on **Mac OS X 10.14.6** 18G6042 darwin-x64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (**Xcode 11.3**)
```

Now, I have different error:

```
..../myfirstflutterapp/ios/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework
    /Modules/JitsiMeet.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:44:35: error: unknown attribute
    '_hasMissingDesignatedInitializers'
    @_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers @objc final public class JMCallKitProxy :
    ObjectiveC.NSObject {
```

This issue should be re-open unless there is a permanent fix.

**Comment by gunschu** [comment] 2020-12-14 19:02
Tested using following, cant reproduce errors being reported

Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (4 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

Xcode Version 12.2 (12B45b)

**Comment by real1900** [comment] 2020-12-14 19:39
This bug occurs on 1.2.0 not 1.0.0

**Comment by gunschu** [comment] 2020-12-14 19:49
Using jitsi_meet 2.0.0 
Published Nov 29, 2020

**Comment by real1900** [comment] 2020-12-15 02:57
Yeah you should be seeing the issue using jitsi_meet 2.0.0. Try flutter clean and build it with Xcode 12.2

**Closed as completed** 2021-04-03 23:29 UTC
Labels: closed for inactivity
